services:
  app:
    image: ghcr.io/tbxark-arc/yunzhijia-status-checker:latest
    pull_policy: always
    volumes:
      - ./config.json:/config.json
    ports:
      - 8999:8999
    restart: always
    command: ["--config", "/config.json"]
